### ISSUE TITLE
Chat for November 8 - 15

### ISSUE THREAD

**Issue by NotNemesis** [madoctopus/Turing#100]
Chat for November 8 to November 15!
Discuss, argue or chat with each other about Turing or non-Turing things :shipit:

**Comment by NotNemesis** [comment]
Oh yes, and issue #100!

**Comment by NotNemesis** [comment]
hey @MC47, [i think i got a project for you](http://github.com/madoctopus/madoctopus.github.io)

**Comment by NotNemesis** [comment]
might change rules about pull requests and such soon

**Comment by sonason** [comment]
Like what?

**Comment by sonason** [comment]
Btw new MSTE update. I think I can make an improvement with the SATCA engine with it.

**Comment by sonason** [comment]
Sorry, horrible at grammar.

**Comment by NotNemesis** [comment]
new pull request rule would be that only i could merge stuff matter what

**Comment by NotNemesis** [comment]
hey, hey @MC47

**Comment by NotNemesis** [comment]
psttttttttttttt...

**Comment by MC47** [comment]
Internet iz s0 s70W

**Comment by NotNemesis** [comment]
1 k |\| 0 \/\/

**Comment by NotNemesis** [comment]
```doot doot```

**Comment by NotNemesis** [comment]
I'm probably going to make seperate repos for each of us on madoctopus, just to give everyone admin privileges on their own projects. I will make a tutorial on how to do this later.

**Comment by MC47** [comment]
Roger but i'm still crap at this

**Comment by NotNemesis** [comment]
you'll figure it out with forking and whatnot

**Comment by MC47** [comment]
k

**Comment by NotNemesis** [comment]
kk
