### ISSUE TITLE
Chat for November 16 - 23

### ISSUE THREAD

**Issue by NotNemesis** [madoctopus/Turing#118]
Get together, talk about anything, and have fun!
``` yay ```

**Comment by NotNemesis** [comment]
Also,  this repo got updated interface!

**Comment by NotNemesis** [comment]
@MC47 here

**Comment by MC47** [comment]
Give meh a song relating to love and unity

**Comment by NotNemesis** [comment]
Steven Universe - Strong than You

**Comment by NotNemesis** [comment]
look it up look it up!

**Comment by NotNemesis** [comment]
Hey guys, check out the new rules [here!](CONTRIBUTING.md)

**Comment by MC47** [comment]
Where dem rules at?

**Comment by NotNemesis** [comment]
updooted it

**Comment by sonason** [comment]
Hi
Looked at the rules. Kinda suck for  my projects but I can't argue

**Comment by NotNemesis** [comment]
I guess i should include that you can pull your own pull requests, no need to wait on me. That's just for creating new files or contributing to something that isn't in your own folder.
