### ISSUE TITLE
Chat for November 24 - December 1

### ISSUE THREAD

**Issue by NotNemesis** [madoctopus/Turing#142]
Chat for Nov 24 to Dec 1. 
Talk, think, and help!

**Comment by sonason** [comment]
New MSTE update

**Comment by NotNemesis** [comment]
@sonason, you can push multiple updates on the same branch and make multiple prs on it too.

**Comment by sonason** [comment]
Thanks, I never knew.

**Comment by sonason** [comment]
The loading screen is genuinly a good idea.

Now if only we can put it in without sacraficing the restart system...

**Comment by NotNemesis** [comment]
what do you mean? how does it sacrifice the restart system?

**Comment by sonason** [comment]
There is a new chat. This is outdated.
