### ISSUE TITLE
Chat for December 12 - January 2

### ISSUE THREAD

**Issue by sonason** [madoctopus/Turing#176]
Chat and discuss whatever you want here!

**Comment by NotNemesis** [comment]
how do we discuss about ``` whatever you want here ``` ??

**Comment by sonason** [comment]
I think we should start with the elephant in the room: the wiki.

**Comment by NotNemesis** [comment]
leave the wiki alone, nothing's wrong with it :p

**Comment by sonason** [comment]
Ok then.

**Comment by sonason** [comment]
Sadly, no Computer Club
