### ISSUE TITLE
Chat for November 1-7

### ISSUE THREAD

**Issue by sonason** [madoctopus/Turing#58]
New chat section for us to get together for the first week of November.

**Comment by NotNemesis** [comment]
Attention all! 
I may be transitioning the Turing repo to an organization account. This will allow us to continue work with our projects and will also allow me to moderate pull and push requests easier. I am unsure when this transition will be but it will be before the month ends.

**Comment by NotNemesis** [comment]
I will transfer ownership of the repo over to a new organization linked to my account so there will be no need to copy and paste files whatsoever.

**Comment by NotNemesis** [comment]
The biggest issue will probably fixing all the URLs within the readme but that will be easy to fix.

**Comment by NotNemesis** [comment]
The other thing that I wanted to say (and ask) was what the new organization should be called. Pulse Labs can't be done as I'll get a copyright strike and a cease and desist notice (it has happened before to others)

**Comment by NotNemesis** [comment]
I was thinking about something along the lines of OddOctopus or oddocto. Once we decide,I will register the new organization

**Comment by NotNemesis** [comment]
or madoctopus

**Comment by NotNemesis** [comment]
https://github.com/madoctopus

**Comment by NotNemesis** [comment]
Mason please delete your fork it's unnecessary as i fixed everything

**Comment by NotNemesis** [comment]
https://github.com/sonason/Turing/settings then delete at the bottom of the page

**Comment by NotNemesis** [comment]
@sonason make sure to name your commits or add a description to show what you have changed. 

CYOAE V xx
> Added xx and fixed bug in issue #xx

Is better than

Updated CYOAE.t
> no description

Because i dont have to spend long to find the changes.

**Comment by sonason** [comment]
Sure

**Comment by NotNemesis** [comment]
https://cloud.githubusercontent.com/assets/13708590/10944016/13ce8f94-82e5-11e5-841f-06ae3d01683c.jpg 
for the logo! Please name it mo and make sure it saves as a jpeg/jpg in the same folder as cyoae!

**Comment by NotNemesis** [comment]
cool little thing i found that you can do with github issues and .md files

if you type 
```
- [ ] (put words here)
```

You can create a checklist like this:
- [ ] @NotNemesis check this off
- [ ] @MC47 check this off
- [ ] @sonason check this off
- [ ] @gabealmeida check this off
